---
stages:
- name: Deploy App
  inputs:
  - type: git
    branch: master
  triggers:
  - type: commit
  jobs:
  - name: Push to Bluemix
    type: deployer
    target:
      url: ${CF_TARGET_URL}
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
      application: ${CF_APP}
    script: |-
      cf push -m 640M "${CF_APP}"
